"""
Interface definitions and data contracts for SAM Windows Control Suite.
Strictly conforms to PROJECT.md lines 226-249, src/sam/common/types.py, and M3 contracts.
"""

from __future__ import annotations
from typing import Any, Dict, List, Optional, Protocol, runtime_checkable
from src.sam.common.types import ExecutionResult


@runtime_checkable
class IAppLauncher(Protocol):
    """Protocol for Windows application lifecycle management."""
    def open_app(self, app_name: str) -> ExecutionResult: ...
    def close_app(self, process_or_name: str) -> ExecutionResult: ...


@runtime_checkable
class IWindowManager(Protocol):
    """Protocol for desktop window state and layout management."""
    def manage_window(self, action: str, window_title: Optional[str] = None) -> ExecutionResult: ...


@runtime_checkable
class IFileController(Protocol):
    """Protocol for atomic filesystem operations and verification."""
    def file_action(self, action: str, **kwargs) -> ExecutionResult: ...


@runtime_checkable
class ISystemController(Protocol):
    """Protocol for hardware controls (volume, brightness, media), diagnostics, and notifications."""
    def control_volume(self, level: Optional[int] = None, delta: Optional[int] = None) -> ExecutionResult: ...
    def control_brightness(self, level: Optional[int] = None) -> ExecutionResult: ...
    def control_media(self, command: str) -> ExecutionResult: ...
    def get_system_stats(self) -> Dict[str, Any]: ...
    def read_notifications(self) -> List[Dict[str, Any]]: ...


@runtime_checkable
class ITerminalRunner(Protocol):
    """Protocol for executing terminal commands with sandboxed timeouts."""
    def run_terminal(self, command: str, shell: str = "powershell", timeout: int = 30) -> ExecutionResult: ...


@runtime_checkable
class IComputerController(Protocol):
    """Unified master controller protocol for Windows computer automation."""
    def open_app(self, app_name: str) -> ExecutionResult: ...
    def close_app(self, process_or_name: str) -> ExecutionResult: ...
    def manage_window(self, action: str, window_title: Optional[str] = None) -> ExecutionResult: ...
    def file_action(self, action: str, **kwargs) -> ExecutionResult: ...
    def control_volume(self, level: Optional[int] = None, delta: Optional[int] = None) -> ExecutionResult: ...
    def control_brightness(self, level: Optional[int] = None) -> ExecutionResult: ...
    def control_media(self, command: str) -> ExecutionResult: ...
    def run_terminal(self, command: str, shell: str = "powershell", timeout: int = 30) -> ExecutionResult: ...
    def get_system_stats(self) -> Dict[str, Any]: ...
    def read_notifications(self) -> List[Dict[str, Any]]: ...
